### ISSUE TITLE
Add email to user information 

### ISSUE THREAD

**Issue by tkg61** [ncecere/exporter-openwebui#4]
**Is your feature request related to a problem? Please describe.**
Instead of user_name being just the first and last of a user which could have a duplicate, can we also add the email address. 

**Describe the solution you'd like**
Additional user attribute as a label of email pulled from the db

**Describe alternatives you've considered**

**Environment Impact**
Will this feature require:
- [x] Database schema changes - maybe?
- [x] New environment variables
- [ ] Additional dependencies
- [x] Changes to existing metrics

**Comment by ncecere** [comment]
This shouldn't be to bad, I think I can have it in soon.

**Comment by ncecere** [comment]
user_email label added in v1.2.0 release
